{% set version = "8.0.5.39" %}

package:
  name: cudnn
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/redist/cudnn/v{{ ".".join(version.split(".")[:3]) }}/cudnn-{{ cuda_compiler_version }}-linux-x64-v{{ version }}.tgz  # [linux64]
  url: https://developer.download.nvidia.com/compute/redist/cudnn/v{{ ".".join(version.split(".")[:3]) }}/cudnn-{{ cuda_compiler_version }}-linux-ppc64le-v{{ version }}.tgz  # [ppc64le]
  url: https://developer.download.nvidia.com/compute/redist/cudnn/v{{ ".".join(version.split(".")[:3]) }}/cudnn-{{ cuda_compiler_version }}-windows10-x64-v{{ version }}.zip  # [win]
  sha256: 2767db23ae2cd869ac008235e2adab81430f951a92a62160884c80ab5902b9e8  # [win64 and cuda_compiler_version == "10.0"]
  sha256: 5e4275d738cc3a105cf6558b70b8a2ff514989ca1cd17bc8515086e20561a652  # [win64 and cuda_compiler_version == "10.1"]
  sha256: fba812f60c61bc33b81db06cd55e8d769774d036186571d724295c71c9936064  # [win64 and cuda_compiler_version == "10.2"]
  sha256: fba812f60c61bc33b81db06cd55e8d769774d036186571d724295c71c9936064  # [win64 and cuda_compiler_version == "11.0"]
  sha256: 28355e395f0b2b93ac2c83b61360b35ba6cd0377e44e78be197b6b61b4b492ba  # [linux64 and cuda_compiler_version == "10.0"]
  sha256: 7eaec8039a2c30ab0bc758d303588767693def6bf49b22485a2c00bf2e136cb3  # [linux64 and cuda_compiler_version == "10.1"]
  sha256: 600267f2caaed2fd58eb214ba669d8ea35f396a7d19b94822e6b36f9f7088c20  # [linux64 and cuda_compiler_version == "10.2"]
  sha256: 600267f2caaed2fd58eb214ba669d8ea35f396a7d19b94822e6b36f9f7088c20  # [linux64 and cuda_compiler_version == "11.0"]

build:
  number: 0
  skip: True   # [cuda_compiler_version == "None" or cuda_compiler_version == "9.2" or cuda_compiler_version == "10.0"]
  script:
    - mkdir -p $PREFIX/include               # [unix]
    - cp include/cudnn.h $PREFIX/include/    # [unix]
    - mkdir -p $PREFIX/lib                   # [unix]
    - mv lib64/libcudnn.so* $PREFIX/lib/     # [linux64]
    - mv lib/libcudnn.so* $PREFIX/lib/       # [ppc64le]
    - mkdir %LIBRARY_INC%                    # [win]
    - copy %SRC_DIR%\\include\\cudnn.h %LIBRARY_INC%\\cudnn.h  # [win]
    - mkdir %LIBRARY_LIB%                    # [win]
    - copy %SRC_DIR%\\lib\\x64\\cudnn.lib %LIBRARY_LIB%\\cudnn.lib  # [win]
    - mkdir %LIBRARY_BIN%                    # [win]
    - copy %SRC_DIR%\\bin\\cudnn64_8.dll %LIBRARY_BIN%\\cudnn64_8.dll  # [win]
  ignore_run_exports_from:
    - {{ compiler('c') }}    # [linux]
  run_exports:
    - {{ pin_subpackage('cudnn') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}
  host:
  run:
    # Only GCC_3.0 or older symbols present
    - libgcc-ng >=3.0     # [linux]
    # Only GLIBCXX_3.4 or older symbols present
    - libstdcxx-ng >=3.4  # [linux]
  run_constrained:
    # Only GLIBC_2.14 or older symbols present
    - __glibc >=2.14       # [linux64]
    # Only GLIBC_2.17 or older symbols present
    - __glibc >=2.17      # [ppc64le]

test:
  commands:
    - if not exist %LIBRARY_INC%/cudnn.h exit 1        # [win]
    - if not exist %LIBRARY_LIB%/cudnn.lib exit 1      # [win]
    - if not exist %LIBRARY_BIN%/cudnn64_8.dll exit 1  # [win]
    - test -f $PREFIX/include/cudnn.h                  # [linux]
    - test -f $PREFIX/lib/libcudnn.so                  # [linux]

about:
  home: https://developer.nvidia.com/cudnn
  license: cuDNN Software License Agreement
  license_file: NVIDIA_SLA_cuDNN_Support.txt
  license_url: https://docs.nvidia.com/deeplearning/cudnn/sla/index.html
  summary: "NVIDIA's cuDNN deep neural network acceleration library"
  description: |
    NVIDIA CUDA Deep Neural Network (cuDNN) is a GPU-accelerated library of
    primitives for deep neural networks. It provides highly tuned
    implementations of routines arising frequently in DNN applications.

    License Agreements:- The packages are governed by the NVIDIA cuDNN
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA cuDNN EULA -
    https://docs.nvidia.com/deeplearning/cudnn/sla/index.html
  doc_url: https://docs.nvidia.com/deeplearning/cudnn/
  dev_url: https://developer.nvidia.com/rdp/cudnn-download

extra:
  recipe-maintainers:
    - isuruf
